# Comprehensive Internet Monitor - Home Assistant Setup
# Updated with Router Health Monitoring and Enhanced Fault Attribution

# MQTT Sensors Configuration
# Add to mqtt.yaml or create mqtt: section in configuration.yaml

mqtt:
  sensor:
    # ============================================================================
    # PRIMARY STATUS
    # ============================================================================
    - name: "Internet Status"
      state_topic: "home/network/sentinel/status/state"
      icon: mdi:web-check
      unique_id: internet_status
      # Values: HEALTHY, OUTAGE_*, DEGRADED_*

    - name: "Internet Fault Blame"
      state_topic: "home/network/sentinel/blame/state"
      icon: mdi:flash-alert
      unique_id: internet_fault_blame
      # WHO IS TO BLAME?
      # Possible values:
      # - NONE (healthy)
      # - ROUTER_CRITICAL (router health < 30/100)
      # - ROUTER_DEGRADED (router health < 60/100)
      # - ROUTER_DOWN (router not responding)
      # - ISP_EQUIPMENT (ISP gateway unreachable)
      # - ISP_DNS (ISP DNS servers down)
      # - ISP_ROUTING (ISP routing/connection issue)
      # - DEGRADED_DNS (partial DNS failure)
      # - DEGRADED_INTERNET (partial connectivity)
      # - DEGRADED_QUALITY (high jitter >50ms)
      # - TRANSIENT (temporary issue)

    - name: "Internet Fault Detail"
      state_topic: "home/network/sentinel/fault_detail/state"
      icon: mdi:text-box-outline
      unique_id: internet_fault_detail

    # ============================================================================
    # ROUTER HEALTH (NEW)
    # ============================================================================
    - name: "Router Health Score"
      state_topic: "home/network/sentinel/router_health_score/state"
      unit_of_measurement: ""
      icon: mdi:heart-pulse
      unique_id: router_health_score
      # 0-100 score based on packet loss, latency, jitter
      # ≥80 = healthy, 60-79 = degraded, <60 = critical

    - name: "Router Packet Loss"
      state_topic: "home/network/sentinel/router_packet_loss/state"
      unit_of_measurement: "%"
      icon: mdi:package-down
      unique_id: router_packet_loss
      # Should be 0%, any packet loss indicates router issues

    - name: "Router Jitter Internal"
      state_topic: "home/network/sentinel/router_jitter_internal/state"
      unit_of_measurement: "ms"
      icon: mdi:sine-wave
      device_class: duration
      unique_id: router_jitter_internal
      # Should be < 2ms, measures latency variance to router

    # ============================================================================
    # LATENCY METRICS
    # ============================================================================
    - name: "Internet Router Latency"
      state_topic: "home/network/sentinel/router_latency/state"
      unit_of_measurement: "ms"
      icon: mdi:router-wireless
      device_class: duration
      unique_id: internet_router_latency

    - name: "Internet DNS Latency"
      state_topic: "home/network/sentinel/dns_latency/state"
      unit_of_measurement: "ms"
      icon: mdi:dns
      device_class: duration
      unique_id: internet_dns_latency

    - name: "Internet HTTP Latency"
      state_topic: "home/network/sentinel/http_latency/state"
      unit_of_measurement: "ms"
      icon: mdi:web
      device_class: duration
      unique_id: internet_http_latency

    - name: "Internet Jitter"
      state_topic: "home/network/sentinel/jitter/state"
      unit_of_measurement: "ms"
      icon: mdi:waveform
      device_class: duration
      unique_id: internet_jitter
      # High jitter (>50ms) indicates unstable connection

    # ============================================================================
    # SUCCESS RATES
    # ============================================================================
    - name: "Internet DNS Success Rate"
      state_topic: "home/network/sentinel/dns_success_rate/state"
      icon: mdi:check-network
      unique_id: internet_dns_success_rate
      # Format: "4/4" (successful/total)

    - name: "Internet HTTP Success Rate"
      state_topic: "home/network/sentinel/http_success_rate/state"
      icon: mdi:check-network
      unique_id: internet_http_success_rate
      # Format: "4/4" (successful/total)

    # ============================================================================
    # SPEED TEST RESULTS
    # ============================================================================
    - name: "Internet Download Speed"
      state_topic: "home/network/sentinel/download_speed/state"
      unit_of_measurement: "Mbit/s"
      icon: mdi:speedometer
      device_class: data_rate
      unique_id: internet_download_speed

    - name: "Internet Speedtest Latency"
      state_topic: "home/network/sentinel/speedtest_latency/state"
      unit_of_measurement: "ms"
      icon: mdi:speedometer
      device_class: duration
      unique_id: internet_speedtest_latency

# ============================================================================
# AUTOMATION EXAMPLES
# ============================================================================

# Automation: Alert on Router Issues
automation:
  - alias: "Alert: Router Health Critical"
    description: "Alert when router health drops below 60/100"
    trigger:
      - platform: numeric_state
        entity_id: sensor.router_health_score
        below: 60
    action:
      - service: notify.mobile_app
        data:
          title: "🔧 Router Health Critical"
          message: >
            Router health score: {{ states('sensor.router_health_score') }}/100
            Packet Loss: {{ states('sensor.router_packet_loss') }}%
            Jitter: {{ states('sensor.router_jitter_internal') }}ms
          data:
            priority: high

  - alias: "Alert: ISP Issue Detected"
    description: "Alert when ISP is at fault"
    trigger:
      - platform: state
        entity_id: sensor.internet_fault_blame
        to: "ISP_EQUIPMENT"
      - platform: state
        entity_id: sensor.internet_fault_blame
        to: "ISP_DNS"
      - platform: state
        entity_id: sensor.internet_fault_blame
        to: "ISP_ROUTING"
    action:
      - service: notify.mobile_app
        data:
          title: "📞 ISP Issue Detected"
          message: "{{ states('sensor.internet_fault_detail') }}"
          data:
            priority: high

  - alias: "Alert: Router Down"
    description: "Alert when router is completely down"
    trigger:
      - platform: state
        entity_id: sensor.internet_fault_blame
        to: "ROUTER_DOWN"
      - platform: state
        entity_id: sensor.internet_fault_blame
        to: "ROUTER_CRITICAL"
    action:
      - service: notify.mobile_app
        data:
          title: "⚠️ Router Issue"
          message: "{{ states('sensor.internet_fault_detail') }} - Check router power and reboot"
          data:
            priority: high
